import type { Metadata } from 'next'
import { Comfortaa, Montserrat_Alternates } from 'next/font/google'

import '../styles/globals.css'

import Navbar from '@/components/Navbar'
import { MainProvider } from '@/components/providers'

const comfortaa = Comfortaa({
	variable: '--font-comfortaa',
	subsets: ['cyrillic', 'latin']
})

const montserratAlternates = Montserrat_Alternates({
	variable: '--font-montserrat-alternates',
	weight: ['500', '600', '700', '800', '900'],
	subsets: ['cyrillic']
})

export const metadata: Metadata = {
	title: {
		template: '%s | MoskvRealty',
		default: 'MoskvRealty'
	},
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`selection:bg-primary/50 relative antialiased ${comfortaa.variable} ${montserratAlternates.variable}`}
			>
				<MainProvider>
					<Navbar />

					{children}
				</MainProvider>
			</body>
		</html>
	)
}
